// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: sever_common.proto

package server_common

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ActionData with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *ActionData) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ActionState

	// no validation rules for ActionStartTime

	// no validation rules for Param

	return nil
}

// ActionDataValidationError is the validation error returned by
// ActionData.Validate if the designated constraints aren't met.
type ActionDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ActionDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ActionDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ActionDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ActionDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ActionDataValidationError) ErrorName() string { return "ActionDataValidationError" }

// Error satisfies the builtin error interface
func (e ActionDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sActionData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ActionDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ActionDataValidationError{}

// Validate checks the field values on PlayerBaseInfo with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PlayerBaseInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PlayerId

	// no validation rules for CharId

	// no validation rules for Name

	// no validation rules for Gold

	// no validation rules for PositionX

	// no validation rules for PositionY

	// no validation rules for PositionZ

	// no validation rules for Orientation

	// no validation rules for Frame

	// no validation rules for Head

	// no validation rules for HeadUrl

	// no validation rules for Model

	// no validation rules for BubbleFrame

	// no validation rules for Coin

	// no validation rules for VehicleID

	if v, ok := interface{}(m.GetActData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PlayerBaseInfoValidationError{
				field:  "ActData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for VipLevel

	// no validation rules for Exp

	// no validation rules for InteractObjID

	// no validation rules for InteractObjSeat

	// no validation rules for NameColor

	// no validation rules for BaseLevel

	// no validation rules for BaseExp

	return nil
}

// PlayerBaseInfoValidationError is the validation error returned by
// PlayerBaseInfo.Validate if the designated constraints aren't met.
type PlayerBaseInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PlayerBaseInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PlayerBaseInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PlayerBaseInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PlayerBaseInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PlayerBaseInfoValidationError) ErrorName() string { return "PlayerBaseInfoValidationError" }

// Error satisfies the builtin error interface
func (e PlayerBaseInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPlayerBaseInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PlayerBaseInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PlayerBaseInfoValidationError{}

// Validate checks the field values on Vec3 with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Vec3) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for X

	// no validation rules for Y

	// no validation rules for Z

	return nil
}

// Vec3ValidationError is the validation error returned by Vec3.Validate if the
// designated constraints aren't met.
type Vec3ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Vec3ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Vec3ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Vec3ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Vec3ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Vec3ValidationError) ErrorName() string { return "Vec3ValidationError" }

// Error satisfies the builtin error interface
func (e Vec3ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVec3.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Vec3ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Vec3ValidationError{}

// Validate checks the field values on UnitInfo with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UnitInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UnitId

	// no validation rules for TypeId

	// no validation rules for PosX

	// no validation rules for PosY

	// no validation rules for PosZ

	// no validation rules for RotateX

	// no validation rules for RotateY

	// no validation rules for RotateZ

	// no validation rules for CanBeCarried

	if v, ok := interface{}(m.GetActData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UnitInfoValidationError{
				field:  "ActData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AttachID

	// no validation rules for AttacheBuildingID

	// no validation rules for BuildingSeat

	// no validation rules for SkinColor

	// no validation rules for Name

	// no validation rules for IsWork

	return nil
}

// UnitInfoValidationError is the validation error returned by
// UnitInfo.Validate if the designated constraints aren't met.
type UnitInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnitInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnitInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnitInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnitInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnitInfoValidationError) ErrorName() string { return "UnitInfoValidationError" }

// Error satisfies the builtin error interface
func (e UnitInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnitInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnitInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnitInfoValidationError{}

// Validate checks the field values on UnitActionData with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *UnitActionData) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ActType

	// no validation rules for ActName

	// no validation rules for ActStartTime

	// no validation rules for ParseType

	// no validation rules for Param

	// no validation rules for EmojiID

	return nil
}

// UnitActionDataValidationError is the validation error returned by
// UnitActionData.Validate if the designated constraints aren't met.
type UnitActionDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnitActionDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnitActionDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnitActionDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnitActionDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnitActionDataValidationError) ErrorName() string { return "UnitActionDataValidationError" }

// Error satisfies the builtin error interface
func (e UnitActionDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnitActionData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnitActionDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnitActionDataValidationError{}

// Validate checks the field values on InteractiveObj with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *InteractiveObj) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for TypeId

	// no validation rules for PosX

	// no validation rules for PosY

	// no validation rules for PosZ

	// no validation rules for RotateX

	// no validation rules for RotateY

	// no validation rules for RotateZ

	// no validation rules for JumpScene

	// no validation rules for JumpBirth

	// no validation rules for LocalData

	// no validation rules for IsRes

	// no validation rules for InterType

	// no validation rules for SubPosX

	// no validation rules for SubPosY

	// no validation rules for SubPosZ

	// no validation rules for Count

	// no validation rules for LastTime

	// no validation rules for Status

	// no validation rules for AreaID

	// no validation rules for ZoomX

	// no validation rules for ZoomY

	// no validation rules for ZoomZ

	// no validation rules for TagID

	// no validation rules for Index

	// no validation rules for GroupID

	// no validation rules for Params

	// no validation rules for Owner

	return nil
}

// InteractiveObjValidationError is the validation error returned by
// InteractiveObj.Validate if the designated constraints aren't met.
type InteractiveObjValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InteractiveObjValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InteractiveObjValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InteractiveObjValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InteractiveObjValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InteractiveObjValidationError) ErrorName() string { return "InteractiveObjValidationError" }

// Error satisfies the builtin error interface
func (e InteractiveObjValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInteractiveObj.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InteractiveObjValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InteractiveObjValidationError{}

// Validate checks the field values on LimitInfo with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *LimitInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Cond

	// no validation rules for InReason

	// no validation rules for OutReason

	// no validation rules for ExpTime

	return nil
}

// LimitInfoValidationError is the validation error returned by
// LimitInfo.Validate if the designated constraints aren't met.
type LimitInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LimitInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LimitInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LimitInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LimitInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LimitInfoValidationError) ErrorName() string { return "LimitInfoValidationError" }

// Error satisfies the builtin error interface
func (e LimitInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLimitInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LimitInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LimitInfoValidationError{}

// Validate checks the field values on RegisterToGateway with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *RegisterToGateway) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Token

	// no validation rules for ServerID

	// no validation rules for ServerType

	// no validation rules for ServerAddr

	// no validation rules for ProcIndex

	// no validation rules for Name

	// no validation rules for MaxPlayer

	// no validation rules for ZoneId

	return nil
}

// RegisterToGatewayValidationError is the validation error returned by
// RegisterToGateway.Validate if the designated constraints aren't met.
type RegisterToGatewayValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterToGatewayValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterToGatewayValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterToGatewayValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterToGatewayValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterToGatewayValidationError) ErrorName() string {
	return "RegisterToGatewayValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterToGatewayValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterToGateway.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterToGatewayValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterToGatewayValidationError{}

// Validate checks the field values on RegisterToGatewayRet with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RegisterToGatewayRet) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Result

	// no validation rules for ZoneId

	return nil
}

// RegisterToGatewayRetValidationError is the validation error returned by
// RegisterToGatewayRet.Validate if the designated constraints aren't met.
type RegisterToGatewayRetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterToGatewayRetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterToGatewayRetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterToGatewayRetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterToGatewayRetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterToGatewayRetValidationError) ErrorName() string {
	return "RegisterToGatewayRetValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterToGatewayRetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterToGatewayRet.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterToGatewayRetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterToGatewayRetValidationError{}

// Validate checks the field values on UpdateOnlineInfo with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *UpdateOnlineInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ProcIndex

	// no validation rules for Name

	// no validation rules for MaxPlayer

	return nil
}

// UpdateOnlineInfoValidationError is the validation error returned by
// UpdateOnlineInfo.Validate if the designated constraints aren't met.
type UpdateOnlineInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateOnlineInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateOnlineInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateOnlineInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateOnlineInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateOnlineInfoValidationError) ErrorName() string { return "UpdateOnlineInfoValidationError" }

// Error satisfies the builtin error interface
func (e UpdateOnlineInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateOnlineInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateOnlineInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateOnlineInfoValidationError{}

// Validate checks the field values on UpdateOnlineInfoRet with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateOnlineInfoRet) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Result

	return nil
}

// UpdateOnlineInfoRetValidationError is the validation error returned by
// UpdateOnlineInfoRet.Validate if the designated constraints aren't met.
type UpdateOnlineInfoRetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateOnlineInfoRetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateOnlineInfoRetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateOnlineInfoRetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateOnlineInfoRetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateOnlineInfoRetValidationError) ErrorName() string {
	return "UpdateOnlineInfoRetValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateOnlineInfoRetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateOnlineInfoRet.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateOnlineInfoRetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateOnlineInfoRetValidationError{}

// Validate checks the field values on GatewayForwardPacket with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GatewayForwardPacket) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Userid

	// no validation rules for PlayerNumber

	// no validation rules for Data

	return nil
}

// GatewayForwardPacketValidationError is the validation error returned by
// GatewayForwardPacket.Validate if the designated constraints aren't met.
type GatewayForwardPacketValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GatewayForwardPacketValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GatewayForwardPacketValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GatewayForwardPacketValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GatewayForwardPacketValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GatewayForwardPacketValidationError) ErrorName() string {
	return "GatewayForwardPacketValidationError"
}

// Error satisfies the builtin error interface
func (e GatewayForwardPacketValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGatewayForwardPacket.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GatewayForwardPacketValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GatewayForwardPacketValidationError{}

// Validate checks the field values on SCKick with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *SCKick) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Kick

	// no validation rules for Contend

	return nil
}

// SCKickValidationError is the validation error returned by SCKick.Validate if
// the designated constraints aren't met.
type SCKickValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SCKickValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SCKickValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SCKickValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SCKickValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SCKickValidationError) ErrorName() string { return "SCKickValidationError" }

// Error satisfies the builtin error interface
func (e SCKickValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSCKick.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SCKickValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SCKickValidationError{}

// Validate checks the field values on ServerMsgData with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ServerMsgData) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PlayerID

	// no validation rules for ServerID

	// no validation rules for Data

	return nil
}

// ServerMsgDataValidationError is the validation error returned by
// ServerMsgData.Validate if the designated constraints aren't met.
type ServerMsgDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServerMsgDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServerMsgDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServerMsgDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServerMsgDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServerMsgDataValidationError) ErrorName() string { return "ServerMsgDataValidationError" }

// Error satisfies the builtin error interface
func (e ServerMsgDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServerMsgData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServerMsgDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServerMsgDataValidationError{}

// Validate checks the field values on BroadcastMsgData with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *BroadcastMsgData) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for MessageId

	// no validation rules for Msg

	return nil
}

// BroadcastMsgDataValidationError is the validation error returned by
// BroadcastMsgData.Validate if the designated constraints aren't met.
type BroadcastMsgDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BroadcastMsgDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BroadcastMsgDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BroadcastMsgDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BroadcastMsgDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BroadcastMsgDataValidationError) ErrorName() string { return "BroadcastMsgDataValidationError" }

// Error satisfies the builtin error interface
func (e BroadcastMsgDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBroadcastMsgData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BroadcastMsgDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BroadcastMsgDataValidationError{}

// Validate checks the field values on GameMsgData with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *GameMsgData) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PlayerID

	// no validation rules for ServerID

	// no validation rules for Data

	return nil
}

// GameMsgDataValidationError is the validation error returned by
// GameMsgData.Validate if the designated constraints aren't met.
type GameMsgDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GameMsgDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GameMsgDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GameMsgDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GameMsgDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GameMsgDataValidationError) ErrorName() string { return "GameMsgDataValidationError" }

// Error satisfies the builtin error interface
func (e GameMsgDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGameMsgData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GameMsgDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GameMsgDataValidationError{}

// Validate checks the field values on RegisterToGame with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *RegisterToGame) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Token

	// no validation rules for ServerID

	// no validation rules for ServerType

	// no validation rules for ServerAddr

	// no validation rules for ScrSerType

	// no validation rules for SerRpcAddr

	return nil
}

// RegisterToGameValidationError is the validation error returned by
// RegisterToGame.Validate if the designated constraints aren't met.
type RegisterToGameValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterToGameValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterToGameValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterToGameValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterToGameValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterToGameValidationError) ErrorName() string { return "RegisterToGameValidationError" }

// Error satisfies the builtin error interface
func (e RegisterToGameValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterToGame.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterToGameValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterToGameValidationError{}

// Validate checks the field values on RegisterToGameRet with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *RegisterToGameRet) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Result

	return nil
}

// RegisterToGameRetValidationError is the validation error returned by
// RegisterToGameRet.Validate if the designated constraints aren't met.
type RegisterToGameRetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterToGameRetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterToGameRetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterToGameRetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterToGameRetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterToGameRetValidationError) ErrorName() string {
	return "RegisterToGameRetValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterToGameRetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterToGameRet.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterToGameRetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterToGameRetValidationError{}

// Validate checks the field values on CreateGame with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *CreateGame) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for SceneId

	// no validation rules for PlayerId

	// no validation rules for WorldServerId

	// no validation rules for GameType

	// no validation rules for GameId

	// no validation rules for Name

	// no validation rules for Nick

	return nil
}

// CreateGameValidationError is the validation error returned by
// CreateGame.Validate if the designated constraints aren't met.
type CreateGameValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateGameValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateGameValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateGameValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateGameValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateGameValidationError) ErrorName() string { return "CreateGameValidationError" }

// Error satisfies the builtin error interface
func (e CreateGameValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateGame.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateGameValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateGameValidationError{}

// Validate checks the field values on CreateGameRet with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CreateGameRet) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Result

	// no validation rules for PlayerId

	return nil
}

// CreateGameRetValidationError is the validation error returned by
// CreateGameRet.Validate if the designated constraints aren't met.
type CreateGameRetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateGameRetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateGameRetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateGameRetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateGameRetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateGameRetValidationError) ErrorName() string { return "CreateGameRetValidationError" }

// Error satisfies the builtin error interface
func (e CreateGameRetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateGameRet.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateGameRetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateGameRetValidationError{}

// Validate checks the field values on SrvMsgToWorldPlayer with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *SrvMsgToWorldPlayer) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PlayerId

	// no validation rules for Data

	return nil
}

// SrvMsgToWorldPlayerValidationError is the validation error returned by
// SrvMsgToWorldPlayer.Validate if the designated constraints aren't met.
type SrvMsgToWorldPlayerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SrvMsgToWorldPlayerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SrvMsgToWorldPlayerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SrvMsgToWorldPlayerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SrvMsgToWorldPlayerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SrvMsgToWorldPlayerValidationError) ErrorName() string {
	return "SrvMsgToWorldPlayerValidationError"
}

// Error satisfies the builtin error interface
func (e SrvMsgToWorldPlayerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSrvMsgToWorldPlayer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SrvMsgToWorldPlayerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SrvMsgToWorldPlayerValidationError{}
