// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: purchase.proto

package purchase

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardAction int32

const (
	CardAction_NOAction      CardAction = 0
	CardAction_DailyReceived CardAction = 1
	CardAction_Buy           CardAction = 2
	CardAction_Renew         CardAction = 3
)

// Enum value maps for CardAction.
var (
	CardAction_name = map[int32]string{
		0: "NOAction",
		1: "DailyReceived",
		2: "Buy",
		3: "Renew",
	}
	CardAction_value = map[string]int32{
		"NOAction":      0,
		"DailyReceived": 1,
		"Buy":           2,
		"Renew":         3,
	}
)

func (x CardAction) Enum() *CardAction {
	p := new(CardAction)
	*p = x
	return p
}

func (x CardAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardAction) Descriptor() protoreflect.EnumDescriptor {
	return file_purchase_proto_enumTypes[0].Descriptor()
}

func (CardAction) Type() protoreflect.EnumType {
	return &file_purchase_proto_enumTypes[0]
}

func (x CardAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardAction.Descriptor instead.
func (CardAction) EnumDescriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{0}
}

var File_purchase_proto protoreflect.FileDescriptor

var file_purchase_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x2a, 0x41, 0x0a, 0x0a, 0x43, 0x61,
	0x72, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x75, 0x79,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x10, 0x03, 0x42, 0x46, 0x5a,
	0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x68, 0x75, 0x68,
	0x61, 0x6f, 0x30, 0x30, 0x2f, 0x67, 0x72, 0x65, 0x61, 0x74, 0x65, 0x73, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73,
	0x65, 0x3b, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0xaa, 0x02, 0x08, 0x70, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_purchase_proto_rawDescOnce sync.Once
	file_purchase_proto_rawDescData = file_purchase_proto_rawDesc
)

func file_purchase_proto_rawDescGZIP() []byte {
	file_purchase_proto_rawDescOnce.Do(func() {
		file_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(file_purchase_proto_rawDescData)
	})
	return file_purchase_proto_rawDescData
}

var file_purchase_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_purchase_proto_goTypes = []interface{}{
	(CardAction)(0), // 0: purchase.CardAction
}
var file_purchase_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_purchase_proto_init() }
func file_purchase_proto_init() {
	if File_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_purchase_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_purchase_proto_goTypes,
		DependencyIndexes: file_purchase_proto_depIdxs,
		EnumInfos:         file_purchase_proto_enumTypes,
	}.Build()
	File_purchase_proto = out.File
	file_purchase_proto_rawDesc = nil
	file_purchase_proto_goTypes = nil
	file_purchase_proto_depIdxs = nil
}
