// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/instantiateType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace instantiateTypeG {

  /// <summary>Holder for reflection information generated from proto/instantiateType.proto</summary>
  public static partial class InstantiateTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/instantiateType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InstantiateTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtwcm90by9pbnN0YW50aWF0ZVR5cGUucHJvdG8SEGluc3RhbnRpYXRlVHlw",
            "ZUcqKAoPSW5zdGFudGlhdGVUeXBlEggKBE5vbmUQABILCgZQbGF5ZXIQkU5C",
            "JVoQL2luc3RhbnRpYXRlVHlwZaoCEGluc3RhbnRpYXRlVHlwZUdiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::instantiateTypeG.InstantiateType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum InstantiateType {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("Player")] Player = 10001,
  }

  #endregion

}

#endregion Designer generated code
