// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: grid.proto

package grid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 三维向量(float)
type PVector3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *PVector3) Reset() {
	*x = PVector3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVector3) ProtoMessage() {}

func (x *PVector3) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVector3.ProtoReflect.Descriptor instead.
func (*PVector3) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{0}
}

func (x *PVector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PVector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PVector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// 二维向量(int)
type PVector2Int struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *PVector2Int) Reset() {
	*x = PVector2Int{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVector2Int) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVector2Int) ProtoMessage() {}

func (x *PVector2Int) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVector2Int.ProtoReflect.Descriptor instead.
func (*PVector2Int) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{1}
}

func (x *PVector2Int) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PVector2Int) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 矩形(int)
type PRectInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *PVector2Int `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"` // 起点坐标
	Size     *PVector2Int `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`         // 大小
}

func (x *PRectInt) Reset() {
	*x = PRectInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grid_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PRectInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRectInt) ProtoMessage() {}

func (x *PRectInt) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRectInt.ProtoReflect.Descriptor instead.
func (*PRectInt) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{2}
}

func (x *PRectInt) GetPosition() *PVector2Int {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PRectInt) GetSize() *PVector2Int {
	if x != nil {
		return x.Size
	}
	return nil
}

// 地面格子
type PGridFloorRect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsShow   bool      `protobuf:"varint,1,opt,name=isShow,proto3" json:"isShow,omitempty"`     // 是否显示
	Name     string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`          // 名字
	Index    int32     `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`       // 编号
	Type     int32     `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`         // 类型
	Dir      int32     `protobuf:"varint,5,opt,name=dir,proto3" json:"dir,omitempty"`           // 方向
	UnlockLv int32     `protobuf:"varint,6,opt,name=unlockLv,proto3" json:"unlockLv,omitempty"` // 解锁等级
	Rect     *PRectInt `protobuf:"bytes,7,opt,name=rect,proto3" json:"rect,omitempty"`          // 矩形
}

func (x *PGridFloorRect) Reset() {
	*x = PGridFloorRect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grid_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PGridFloorRect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGridFloorRect) ProtoMessage() {}

func (x *PGridFloorRect) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGridFloorRect.ProtoReflect.Descriptor instead.
func (*PGridFloorRect) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{3}
}

func (x *PGridFloorRect) GetIsShow() bool {
	if x != nil {
		return x.IsShow
	}
	return false
}

func (x *PGridFloorRect) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PGridFloorRect) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PGridFloorRect) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PGridFloorRect) GetDir() int32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *PGridFloorRect) GetUnlockLv() int32 {
	if x != nil {
		return x.UnlockLv
	}
	return 0
}

func (x *PGridFloorRect) GetRect() *PRectInt {
	if x != nil {
		return x.Rect
	}
	return nil
}

var File_grid_proto protoreflect.FileDescriptor

var file_grid_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72,
	0x69, 0x64, 0x22, 0x34, 0x0a, 0x08, 0x50, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x29, 0x0a, 0x0b, 0x50, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x32, 0x49, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x79, 0x22, 0x60, 0x0a, 0x08, 0x50, 0x52, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x74, 0x12,
	0x2d, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x50, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x32, 0x49, 0x6e, 0x74, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67,
	0x72, 0x69, 0x64, 0x2e, 0x50, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x49, 0x6e, 0x74, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x0e, 0x50, 0x47, 0x72, 0x69, 0x64, 0x46,
	0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x53, 0x68,
	0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x68, 0x6f, 0x77,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x69, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x4c, 0x76, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x4c, 0x76, 0x12, 0x22, 0x0a, 0x04,
	0x72, 0x65, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x69,
	0x64, 0x2e, 0x50, 0x52, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x04, 0x72, 0x65, 0x63, 0x74,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x68, 0x75, 0x68, 0x61, 0x6f, 0x30, 0x30, 0x2f, 0x67, 0x72, 0x65, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x69, 0x64,
	0x3b, 0x67, 0x72, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grid_proto_rawDescOnce sync.Once
	file_grid_proto_rawDescData = file_grid_proto_rawDesc
)

func file_grid_proto_rawDescGZIP() []byte {
	file_grid_proto_rawDescOnce.Do(func() {
		file_grid_proto_rawDescData = protoimpl.X.CompressGZIP(file_grid_proto_rawDescData)
	})
	return file_grid_proto_rawDescData
}

var file_grid_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grid_proto_goTypes = []interface{}{
	(*PVector3)(nil),       // 0: grid.PVector3
	(*PVector2Int)(nil),    // 1: grid.PVector2Int
	(*PRectInt)(nil),       // 2: grid.PRectInt
	(*PGridFloorRect)(nil), // 3: grid.PGridFloorRect
}
var file_grid_proto_depIdxs = []int32{
	1, // 0: grid.PRectInt.position:type_name -> grid.PVector2Int
	1, // 1: grid.PRectInt.size:type_name -> grid.PVector2Int
	2, // 2: grid.PGridFloorRect.rect:type_name -> grid.PRectInt
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grid_proto_init() }
func file_grid_proto_init() {
	if File_grid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVector3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVector2Int); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grid_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PRectInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grid_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PGridFloorRect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grid_proto_goTypes,
		DependencyIndexes: file_grid_proto_depIdxs,
		MessageInfos:      file_grid_proto_msgTypes,
	}.Build()
	File_grid_proto = out.File
	file_grid_proto_rawDesc = nil
	file_grid_proto_goTypes = nil
	file_grid_proto_depIdxs = nil
}
