// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: scene.proto

package scene

import (
	server_common "github.com/phuhao00/greatestworks-proto/server_common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinSceneError int32

const (
	JoinSceneError_VisitSceneError    JoinSceneError = 0 // 位置错误(可能是配表错了)
	JoinSceneError_VisitSceneUnlocked JoinSceneError = 1 // 新手农庄未解锁
	JoinSceneError_VisitSceneCrowded  JoinSceneError = 2 // 访问的场景人太多了
)

// Enum value maps for JoinSceneError.
var (
	JoinSceneError_name = map[int32]string{
		0: "VisitSceneError",
		1: "VisitSceneUnlocked",
		2: "VisitSceneCrowded",
	}
	JoinSceneError_value = map[string]int32{
		"VisitSceneError":    0,
		"VisitSceneUnlocked": 1,
		"VisitSceneCrowded":  2,
	}
)

func (x JoinSceneError) Enum() *JoinSceneError {
	p := new(JoinSceneError)
	*p = x
	return p
}

func (x JoinSceneError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinSceneError) Descriptor() protoreflect.EnumDescriptor {
	return file_scene_proto_enumTypes[0].Descriptor()
}

func (JoinSceneError) Type() protoreflect.EnumType {
	return &file_scene_proto_enumTypes[0]
}

func (x JoinSceneError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinSceneError.Descriptor instead.
func (JoinSceneError) EnumDescriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{0}
}

type SceneHeartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *SceneHeartbeat) Reset() {
	*x = SceneHeartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneHeartbeat) ProtoMessage() {}

func (x *SceneHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneHeartbeat.ProtoReflect.Descriptor instead.
func (*SceneHeartbeat) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{0}
}

func (x *SceneHeartbeat) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type CSCanJoinScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId  int32  `protobuf:"varint,1,opt,name=sceneId,proto3" json:"sceneId,omitempty"`
	PlayerId uint64 `protobuf:"varint,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *CSCanJoinScene) Reset() {
	*x = CSCanJoinScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSCanJoinScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSCanJoinScene) ProtoMessage() {}

func (x *CSCanJoinScene) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSCanJoinScene.ProtoReflect.Descriptor instead.
func (*CSCanJoinScene) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{1}
}

func (x *CSCanJoinScene) GetSceneId() int32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *CSCanJoinScene) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type SCCanJoinScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk     bool   `protobuf:"varint,1,opt,name=isOk,proto3" json:"isOk,omitempty"`         //
	SceneId  int32  `protobuf:"varint,2,opt,name=sceneId,proto3" json:"sceneId,omitempty"`   // 跳转的场景ID
	PlayerId uint64 `protobuf:"varint,3,opt,name=playerId,proto3" json:"playerId,omitempty"` //
}

func (x *SCCanJoinScene) Reset() {
	*x = SCCanJoinScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCCanJoinScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCCanJoinScene) ProtoMessage() {}

func (x *SCCanJoinScene) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCCanJoinScene.ProtoReflect.Descriptor instead.
func (*SCCanJoinScene) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{2}
}

func (x *SCCanJoinScene) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *SCCanJoinScene) GetSceneId() int32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SCCanJoinScene) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type CSJoinScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId  int32    `protobuf:"varint,1,opt,name=sceneId,proto3" json:"sceneId,omitempty"`   // 跳转的场景ID
	BirthId  uint32   `protobuf:"varint,2,opt,name=birthId,proto3" json:"birthId,omitempty"`   // 传送点ID
	PlayerId uint64   `protobuf:"varint,3,opt,name=playerId,proto3" json:"playerId,omitempty"` // 如果playerId != 0 表示进入玩家家园场景
	Passwd   string   `protobuf:"bytes,4,opt,name=passwd,proto3" json:"passwd,omitempty"`      //
	Gift     []uint32 `protobuf:"varint,5,rep,packed,name=gift,proto3" json:"gift,omitempty"`  // 伴手礼
	IsView   bool     `protobuf:"varint,6,opt,name=isView,proto3" json:"isView,omitempty"`     // 是否观众
	JumpType uint32   `protobuf:"varint,7,opt,name=jumpType,proto3" json:"jumpType,omitempty"` // 切场景原因类型(0:传送阵 1:任务切场景 2:区块出生点)
	Param    uint32   `protobuf:"varint,8,opt,name=param,proto3" json:"param,omitempty"`       // jumpType=1 param=task step id
	Portal   string   `protobuf:"bytes,9,opt,name=portal,proto3" json:"portal,omitempty"`      // 传送门数据
}

func (x *CSJoinScene) Reset() {
	*x = CSJoinScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSJoinScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSJoinScene) ProtoMessage() {}

func (x *CSJoinScene) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSJoinScene.ProtoReflect.Descriptor instead.
func (*CSJoinScene) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{3}
}

func (x *CSJoinScene) GetSceneId() int32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *CSJoinScene) GetBirthId() uint32 {
	if x != nil {
		return x.BirthId
	}
	return 0
}

func (x *CSJoinScene) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CSJoinScene) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *CSJoinScene) GetGift() []uint32 {
	if x != nil {
		return x.Gift
	}
	return nil
}

func (x *CSJoinScene) GetIsView() bool {
	if x != nil {
		return x.IsView
	}
	return false
}

func (x *CSJoinScene) GetJumpType() uint32 {
	if x != nil {
		return x.JumpType
	}
	return 0
}

func (x *CSJoinScene) GetParam() uint32 {
	if x != nil {
		return x.Param
	}
	return 0
}

func (x *CSJoinScene) GetPortal() string {
	if x != nil {
		return x.Portal
	}
	return ""
}

type SCJoinScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId    int32                           `protobuf:"varint,1,opt,name=sceneId,proto3" json:"sceneId,omitempty"`      // 跳转的场景ID
	PlayerInfo *server_common.PlayerBaseInfo   `protobuf:"bytes,2,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"` // 玩家数据
	Players    []*server_common.PlayerBaseInfo `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`       //不包括自己
}

func (x *SCJoinScene) Reset() {
	*x = SCJoinScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCJoinScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCJoinScene) ProtoMessage() {}

func (x *SCJoinScene) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCJoinScene.ProtoReflect.Descriptor instead.
func (*SCJoinScene) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{4}
}

func (x *SCJoinScene) GetSceneId() int32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SCJoinScene) GetPlayerInfo() *server_common.PlayerBaseInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

func (x *SCJoinScene) GetPlayers() []*server_common.PlayerBaseInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type SCJoinSceneError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode JoinSceneError `protobuf:"varint,1,opt,name=errCode,proto3,enum=scene.JoinSceneError" json:"errCode,omitempty"`
}

func (x *SCJoinSceneError) Reset() {
	*x = SCJoinSceneError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCJoinSceneError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCJoinSceneError) ProtoMessage() {}

func (x *SCJoinSceneError) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCJoinSceneError.ProtoReflect.Descriptor instead.
func (*SCJoinSceneError) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{5}
}

func (x *SCJoinSceneError) GetErrCode() JoinSceneError {
	if x != nil {
		return x.ErrCode
	}
	return JoinSceneError_VisitSceneError
}

type SCPlayerJoinScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerInfo *server_common.PlayerBaseInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"` // 拉姆数据
}

func (x *SCPlayerJoinScene) Reset() {
	*x = SCPlayerJoinScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCPlayerJoinScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCPlayerJoinScene) ProtoMessage() {}

func (x *SCPlayerJoinScene) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCPlayerJoinScene.ProtoReflect.Descriptor instead.
func (*SCPlayerJoinScene) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{6}
}

func (x *SCPlayerJoinScene) GetPlayerInfo() *server_common.PlayerBaseInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

type CSLeaveScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSLeaveScene) Reset() {
	*x = CSLeaveScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSLeaveScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSLeaveScene) ProtoMessage() {}

func (x *CSLeaveScene) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSLeaveScene.ProtoReflect.Descriptor instead.
func (*CSLeaveScene) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{7}
}

type SCLeaveScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Playerid uint64 `protobuf:"varint,1,opt,name=playerid,proto3" json:"playerid,omitempty"`
}

func (x *SCLeaveScene) Reset() {
	*x = SCLeaveScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCLeaveScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCLeaveScene) ProtoMessage() {}

func (x *SCLeaveScene) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCLeaveScene.ProtoReflect.Descriptor instead.
func (*SCLeaveScene) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{8}
}

func (x *SCLeaveScene) GetPlayerid() uint64 {
	if x != nil {
		return x.Playerid
	}
	return 0
}

// 进入视野
type SCPlayerEnterScreen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerInfo *server_common.PlayerBaseInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
}

func (x *SCPlayerEnterScreen) Reset() {
	*x = SCPlayerEnterScreen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCPlayerEnterScreen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCPlayerEnterScreen) ProtoMessage() {}

func (x *SCPlayerEnterScreen) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCPlayerEnterScreen.ProtoReflect.Descriptor instead.
func (*SCPlayerEnterScreen) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{9}
}

func (x *SCPlayerEnterScreen) GetPlayerInfo() *server_common.PlayerBaseInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// 离开视野
type SCPlayerLeaveScreen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *SCPlayerLeaveScreen) Reset() {
	*x = SCPlayerLeaveScreen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCPlayerLeaveScreen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCPlayerLeaveScreen) ProtoMessage() {}

func (x *SCPlayerLeaveScreen) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCPlayerLeaveScreen.ProtoReflect.Descriptor instead.
func (*SCPlayerLeaveScreen) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{10}
}

func (x *SCPlayerLeaveScreen) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 同步场景内的单位信息(进场景同步-单位数据不包括玩家,玩家通过单独的协议同步)
type SCSyncUnitsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Units []*server_common.UnitInfo `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
}

func (x *SCSyncUnitsInfo) Reset() {
	*x = SCSyncUnitsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCSyncUnitsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCSyncUnitsInfo) ProtoMessage() {}

func (x *SCSyncUnitsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCSyncUnitsInfo.ProtoReflect.Descriptor instead.
func (*SCSyncUnitsInfo) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{11}
}

func (x *SCSyncUnitsInfo) GetUnits() []*server_common.UnitInfo {
	if x != nil {
		return x.Units
	}
	return nil
}

// 单位进入视野范围
type SCUnitEnterScreen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit *server_common.UnitInfo `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *SCUnitEnterScreen) Reset() {
	*x = SCUnitEnterScreen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUnitEnterScreen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUnitEnterScreen) ProtoMessage() {}

func (x *SCUnitEnterScreen) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUnitEnterScreen.ProtoReflect.Descriptor instead.
func (*SCUnitEnterScreen) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{12}
}

func (x *SCUnitEnterScreen) GetUnit() *server_common.UnitInfo {
	if x != nil {
		return x.Unit
	}
	return nil
}

// 单位离开视野范围
type SCUnitLeaveScreen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId uint64 `protobuf:"varint,1,opt,name=unitId,proto3" json:"unitId,omitempty"`
}

func (x *SCUnitLeaveScreen) Reset() {
	*x = SCUnitLeaveScreen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUnitLeaveScreen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUnitLeaveScreen) ProtoMessage() {}

func (x *SCUnitLeaveScreen) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUnitLeaveScreen.ProtoReflect.Descriptor instead.
func (*SCUnitLeaveScreen) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{13}
}

func (x *SCUnitLeaveScreen) GetUnitId() uint64 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

// 单位信息更新
type SCUnitInfoUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit *server_common.UnitInfo `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *SCUnitInfoUpdate) Reset() {
	*x = SCUnitInfoUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scene_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUnitInfoUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUnitInfoUpdate) ProtoMessage() {}

func (x *SCUnitInfoUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUnitInfoUpdate.ProtoReflect.Descriptor instead.
func (*SCUnitInfoUpdate) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{14}
}

func (x *SCUnitInfoUpdate) GetUnit() *server_common.UnitInfo {
	if x != nil {
		return x.Unit
	}
	return nil
}

var File_scene_proto protoreflect.FileDescriptor

var file_scene_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x1a, 0x12, 0x73, 0x65, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0e, 0x53, 0x63, 0x65, 0x6e,
	0x65, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x46,
	0x0a, 0x0e, 0x43, 0x53, 0x43, 0x61, 0x6e, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x0e, 0x53, 0x43, 0x43, 0x61, 0x6e, 0x4a,
	0x6f, 0x69, 0x6e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x4f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x22, 0xeb, 0x01, 0x0a, 0x0b, 0x43, 0x53, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x62, 0x69, 0x72, 0x74, 0x68, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62,
	0x69, 0x72, 0x74, 0x68, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x69,
	0x66, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04, 0x67, 0x69, 0x66, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x73, 0x56, 0x69, 0x65, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x69, 0x73, 0x56, 0x69, 0x65, 0x77, 0x12, 0x1a, 0x0a, 0x08, 0x6a, 0x75, 0x6d, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6a, 0x75, 0x6d, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x72, 0x74,
	0x61, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c,
	0x22, 0x9d, 0x01, 0x0a, 0x0b, 0x53, 0x43, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0a, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x36, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42,
	0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x22, 0x43, 0x0a, 0x10, 0x53, 0x43, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x4a, 0x6f,
	0x69, 0x6e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x07, 0x65, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x51, 0x0a, 0x11, 0x53, 0x43, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x53, 0x4c, 0x65,
	0x61, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x22, 0x2a, 0x0a, 0x0c, 0x53, 0x43, 0x4c, 0x65,
	0x61, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x13, 0x53, 0x43, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x3c, 0x0a, 0x0a, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x31, 0x0a, 0x13, 0x53, 0x43, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x0f,
	0x53, 0x43, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x2c, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x6e,
	0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x22, 0x3f, 0x0a,
	0x11, 0x53, 0x43, 0x55, 0x6e, 0x69, 0x74, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x12, 0x2a, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x55, 0x6e, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0x2b,
	0x0a, 0x11, 0x53, 0x43, 0x55, 0x6e, 0x69, 0x74, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x63, 0x72,
	0x65, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x10, 0x53,
	0x43, 0x55, 0x6e, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x2a, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x6e, 0x69,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x2a, 0x54, 0x0a, 0x0e, 0x4a,
	0x6f, 0x69, 0x6e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x13, 0x0a,
	0x0f, 0x56, 0x69, 0x73, 0x69, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x56, 0x69, 0x73, 0x69, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x56, 0x69,
	0x73, 0x69, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x43, 0x72, 0x6f, 0x77, 0x64, 0x65, 0x64, 0x10,
	0x02, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x68, 0x75, 0x68, 0x61, 0x6f, 0x30, 0x30, 0x2f, 0x67, 0x72, 0x65, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x3b, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scene_proto_rawDescOnce sync.Once
	file_scene_proto_rawDescData = file_scene_proto_rawDesc
)

func file_scene_proto_rawDescGZIP() []byte {
	file_scene_proto_rawDescOnce.Do(func() {
		file_scene_proto_rawDescData = protoimpl.X.CompressGZIP(file_scene_proto_rawDescData)
	})
	return file_scene_proto_rawDescData
}

var file_scene_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_scene_proto_goTypes = []interface{}{
	(JoinSceneError)(0),                  // 0: scene.JoinSceneError
	(*SceneHeartbeat)(nil),               // 1: scene.SceneHeartbeat
	(*CSCanJoinScene)(nil),               // 2: scene.CSCanJoinScene
	(*SCCanJoinScene)(nil),               // 3: scene.SCCanJoinScene
	(*CSJoinScene)(nil),                  // 4: scene.CSJoinScene
	(*SCJoinScene)(nil),                  // 5: scene.SCJoinScene
	(*SCJoinSceneError)(nil),             // 6: scene.SCJoinSceneError
	(*SCPlayerJoinScene)(nil),            // 7: scene.SCPlayerJoinScene
	(*CSLeaveScene)(nil),                 // 8: scene.CSLeaveScene
	(*SCLeaveScene)(nil),                 // 9: scene.SCLeaveScene
	(*SCPlayerEnterScreen)(nil),          // 10: scene.SCPlayerEnterScreen
	(*SCPlayerLeaveScreen)(nil),          // 11: scene.SCPlayerLeaveScreen
	(*SCSyncUnitsInfo)(nil),              // 12: scene.SCSyncUnitsInfo
	(*SCUnitEnterScreen)(nil),            // 13: scene.SCUnitEnterScreen
	(*SCUnitLeaveScreen)(nil),            // 14: scene.SCUnitLeaveScreen
	(*SCUnitInfoUpdate)(nil),             // 15: scene.SCUnitInfoUpdate
	(*server_common.PlayerBaseInfo)(nil), // 16: ServerCommon.PlayerBaseInfo
	(*server_common.UnitInfo)(nil),       // 17: ServerCommon.UnitInfo
}
var file_scene_proto_depIdxs = []int32{
	16, // 0: scene.SCJoinScene.playerInfo:type_name -> ServerCommon.PlayerBaseInfo
	16, // 1: scene.SCJoinScene.players:type_name -> ServerCommon.PlayerBaseInfo
	0,  // 2: scene.SCJoinSceneError.errCode:type_name -> scene.JoinSceneError
	16, // 3: scene.SCPlayerJoinScene.playerInfo:type_name -> ServerCommon.PlayerBaseInfo
	16, // 4: scene.SCPlayerEnterScreen.playerInfo:type_name -> ServerCommon.PlayerBaseInfo
	17, // 5: scene.SCSyncUnitsInfo.units:type_name -> ServerCommon.UnitInfo
	17, // 6: scene.SCUnitEnterScreen.unit:type_name -> ServerCommon.UnitInfo
	17, // 7: scene.SCUnitInfoUpdate.unit:type_name -> ServerCommon.UnitInfo
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_scene_proto_init() }
func file_scene_proto_init() {
	if File_scene_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scene_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneHeartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSCanJoinScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCCanJoinScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSJoinScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCJoinScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCJoinSceneError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCPlayerJoinScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSLeaveScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCLeaveScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCPlayerEnterScreen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCPlayerLeaveScreen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCSyncUnitsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUnitEnterScreen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUnitLeaveScreen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scene_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUnitInfoUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scene_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scene_proto_goTypes,
		DependencyIndexes: file_scene_proto_depIdxs,
		EnumInfos:         file_scene_proto_enumTypes,
		MessageInfos:      file_scene_proto_msgTypes,
	}.Build()
	File_scene_proto = out.File
	file_scene_proto_rawDesc = nil
	file_scene_proto_goTypes = nil
	file_scene_proto_depIdxs = nil
}
