// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: rank.proto

package rank

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on RankMember with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *RankMember) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Index

	// no validation rules for PlayerId

	// no validation rules for Score

	// no validation rules for Name

	// no validation rules for Head

	// no validation rules for HeadFrame

	return nil
}

// RankMemberValidationError is the validation error returned by
// RankMember.Validate if the designated constraints aren't met.
type RankMemberValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RankMemberValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RankMemberValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RankMemberValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RankMemberValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RankMemberValidationError) ErrorName() string { return "RankMemberValidationError" }

// Error satisfies the builtin error interface
func (e RankMemberValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRankMember.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RankMemberValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RankMemberValidationError{}

// Validate checks the field values on RankData with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *RankData) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for RankID

	for idx, item := range m.GetMembers() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RankDataValidationError{
					field:  fmt.Sprintf("Members[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// RankDataValidationError is the validation error returned by
// RankData.Validate if the designated constraints aren't met.
type RankDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RankDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RankDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RankDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RankDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RankDataValidationError) ErrorName() string { return "RankDataValidationError" }

// Error satisfies the builtin error interface
func (e RankDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRankData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RankDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RankDataValidationError{}
